name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Set up environment variables
        run: echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" >> .env.local

      - name: Build React app
        run: npm run build

      - name: Verify build success
        run: |
          if [ -d "build" ]; then
            echo "Build successful"
          else
            echo "Build failed"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build

      - name: Merge pull request
        if: github.event_name == 'pull_request' && success()
        uses: octokit/rest.js@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await octokit.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              commit_title: 'Automated merge',
              commit_message: `Automated merge of pull request ${context.payload.pull_request.number}`
            });
            console.log(response);
